### ISSUE TITLE
Link selection

### ISSUE THREAD

**Issue by deivijt** [projectstorm/react-diagrams#110]
Is it possible to change that when I click on a link this is selected without having to go to the combination with the shift key?

**Comment by dylanvorster** [comment]
I think we need to implement better key mapping, I'll add this to the roadmap.

**Comment by smeijer** [comment]
I'm also in favor of this. The behavior in Microsoft Visio makes sense to me. It's as follows:

| visio | current behavior |
|-------|---------|
| <kbd>left-click</kbd> selects a `link` (connector). | <kbd>shift</kbd> + <kbd>left-click</kbd> |
| <kbd>Ctrl</kbd> + <kbd>left-click</kbd> on a `mid-point` inserts a new `vertice`. | <kbd>left-click</kbd> on link |
| <kbd>Ctrl</kbd> + <kbd>left-click</kbd> + <kbd>mouse-drag</kbd> clones the current selection. | - |

The last one (clone with hotkey) is currently unavailable in this project. If it would be implemented, I would certainly go for an option to make it configurable.

`mid-points` are currently not present on the default-link. I don't expect that it would be very hard to implement though. If unwanted for some reason, you could also make it so that <kbd>Ctrl</kbd> + <kbd>left-click</kbd> on the link itself inserts a `vertice`. 

This, however, will come back at you when you'll decide to implement something like the Visio clone functionality.

**Comment by dylanvorster** [comment]
@smeijer Im not really for changing the defaults. I for example, prefer the point being added because I want the system to work more like a process designer that emulates LabView more closely. The solution to the problem however, is to support a keymap object as mentioned that defines all of the rules including the defaults. (fwiw Im not really a fan of Viso, I much prefer lucid chart of OmniGraffle)

**Comment by dylanvorster** [comment]
it was something I was going to take a look at in 5.0.0 but never got around to, will probably add it in 5.1

**Comment by smeijer** [comment]
@dylanvorster, Sounds like a solid plan. 👍 

I guess that relates #166 to this issue. The described problem is different, but it sounds like your proposed solution solves that one too.

**Comment by smeijer** [comment]
Sorry, there was even an older issue: #49. So that one is related too. I like your proposed solution there:

> I feel like that would make the feature very hidden, and i really like how its already so intuitive to just click and drag to add points. I think I'm going to implement the click to select, but click + drag to create point system. I will add a little bit of a threshold so that you have to move the mouse more than 5px or something to trigger it.

**Comment by dylanvorster** [comment]
All of this can now be done using the new Hierarchal state machine and event bus (basically by plugging in your own behaviour)

**Comment by mecirmartin** [comment]
@dylanvorster Hey, could you explain more clearyly how this could be done?
Thanks
