### ISSUE TITLE
Use of setState in componentWillUpdate of DiagramWidget

### ISSUE THREAD

**Issue by chlumper** [projectstorm/react-diagrams#165]
Hi!

Just saw that the library uses `setState()` in the `componentWillUpdate` function of `DiagramWidget `which shouldn't be done according to the React documentation.
https://reactjs.org/docs/react-component.html#componentwillupdate

https://github.com/projectstorm/react-diagrams/blob/29ca66989c4c5803eef066113c85db92fba7076c/src/widgets/DiagramWidget.tsx#L93-L102

Haven't had time think a about a different solution but it might be sufficient to move this part into `componentWillReceiveProps() `.

Some explanations for the react lifecycle methods http://busypeoples.github.io/post/react-component-lifecycle/

Thanks!

btw: Great library!

**Comment by dylanvorster** [comment]
Hi there, This is by design because we need to trigger a secondary render cycle so that the links can target the DOM nodes in the top layer. We dont always call set state there and moving the logic to component should update only controls how the current render cycle should perform. This library pushes react to its limits so we purposefully break a few “rules” here and there :)
