### ISSUE TITLE
Usage with JSX

### ISSUE THREAD

**Issue by m4rcelofs** [projectstorm/react-diagrams#21]
The demos create everything on `window.onload` and render directly to `document.body`.
The closest thing I could find was [adventure-weave's index.tsx](https://github.com/mwozniczak/adventure-weave/blob/master/src/index.tsx) which returns a `DiagramWidget` on its `render()`, but that's just a wrapper and the actual work is also done during `window.onload`.

In my case that wouldn't really work - I already have a full app with redux, grommet, routing, other "pages" (so the diagram would not be always visible), etc. The ideal way would be for `DiagramWidget` to be wrapped by a `Component` that abstracts all that and just renders the diagram in the provided div, I guess.

I realize you guys are not fans of JSX, but many people don't really have an option there (: - plus the "default" way to start learning React usually uses JSX.

Apologies if this looks like a noobish request, but Is there an example about linking it? What would be the best way to do it?

**Comment by alexisvincent** [comment]
@dylanvorster Essentially @m4rcelofs is asking for an example/way to use react-diagrams in a declarative manner. If I understand correctly. Which would add value to the project.

**Comment by dylanvorster** [comment]
I don't know if I'm being genuinely stupid, but I'm not kidding or even remotely joking or being sarcastic when I say I seriously don't understand the issue being talked about here.

My demos render directly into the body because thats the simplest possible way of giving a demo?
The system is treated exactly like any other react widget. Whether you use redux, Mox, JSX, vanilla JS, render on the server, browser, use coffee script, render it with JQuery.. whatever else you think of, is to me completely irrelevant because its just a react widget. The DiagramWidget is the view, and the DiagramModel is the model, if you store the model somewhere in your application, hide the DiagramWidget and then show the DiagramWidget again, with the same model (aka pass the same props in again), the system just continues where it is left off, like any other stateless react widget.

Like JSX is literally just another way of writing the code, it doesn't have any single effect on the functionality of any system that is written with it, which is the primary reason I don't understand what the issue is about. I use this library on multiple pages that are constantly hiding and showing, and have no issue with it doing so...?

So maybe if you could just explain to me what it is you are trying to do, that is not doing what it should be doing, or explain to me with a code example what you want to achieve, but currently can't (and if applicable, explain to me where and why JSX and Redux has anything to do with this) , ill jump onto a fix/implementation right away, or happily discuss options or changes we can make.

But I'm really confused with the subject matter of this issue xD (sorry if it sounds like I'm ranting)

**Comment by m4rcelofs** [comment]
Well, its really not about anything lacking the lib - apologies if it sounded like that. Its just that I'm fairly new to React (and TypeScript) and it's been a bit difficult for me to get something running in a declarative way, but I'm probably just missing something quite basic.

For instance, the best I figured was [this](https://bitbucket.org/marcelofs/react-diagrams-example/src/76df8771a3e1c9794b0a96a1e87730e5d1a65083/src/Diagram.js?at=master&fileviewer=file-view-default) (clone and `npm start` should show something in `localhost:3000`), and it indeed does seem that all elements are in the DOM, it just doesn't show anything.

Since it's probably something stupid I'm doing, I figured I'd ask for a JSX example (:

**Comment by dylanvorster** [comment]
Yeah that is probably because you are missing some css (that example is correct). Check that the diagram widget is in fact expanding to the full size of the browser window. My demos import some additional css to make that possible. See this: https://github.com/projectstorm/react-diagrams/blob/master/demos/test.scss

Im not sure if you are doing something similar, but thats potentially the cause. The other thing is that in  your example, you have your logic that works with the model, inside your own class, which is akin to saying that your business logic is inside your view, when that logic should really be inside a store (that doesnt rely on your component being mounted or updated.)

Thats why my demos have the logic in the window.onload, its because like any react program, your state of the application should not be stored inside your react widgets. Thats also why its called "React" its so that you can have a user-interface that renders your application state.

**Comment by dylanvorster** [comment]
So i would move ``` this.engine = new DiagramEngine();``` and all that logic that is in your constructor, rather into your redux stores, and then simply pass in the diagram model when you want to render it.

**Comment by m4rcelofs** [comment]
Ha, totally correct - and a totally stupid mistake (forgot to set `.storm-diagrams-canvas` to 100% width/height, was only setting its parent). Thanks for the other pointers too! I might be bugging you guys a little until I understand the lib better (:
