### ISSUE TITLE
[HELP] Migration from 3.1.4 to 5.1.1

### ISSUE THREAD

**Issue by Nandez89** [projectstorm/react-diagrams#240]
Hello, 
I'm updating from version 3.1.4 to 5.1.1 and I understand there are quite a few breaking changes. I was wondering if there's a migration guide? I have been looking around but so far I can only see the new examples and try to find the differences.

Can you point me in the right direction, thanks in advance!

**Comment by dylanvorster** [comment]
Unfortunately there isn't an official guide :(

What I can suggest is:
* going through the change-log file
* comparing the simple demo to how it looked in version 3 (look at the tag)
* reading through the blog posts that cover the release notes.

Things to consider:
* There is just one factory for each model now, it used to be two (one for serialization/deserialization)
* rather use mutators instead of just re-assigning properties
* a few changes to some of the listeners
* lots of internal changes, but they shouldn't _really_ have a major affect on the front facing API
