### ISSUE TITLE
Add only used lodash functions as dependencies instead of the full lodash lib

### ISSUE THREAD

**Issue by alexandrudanpop** [projectstorm/react-diagrams#313]
I like this library and want to use it for our production app as a diagrams library. 

Could we please dump lodash and import only the used functions? This will decrese bundle size in the final apps.

https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark

**Comment by dylanvorster** [comment]
Have been burned in the past for importing very specific lodash functions, and the gzipped size of the production build is 30kb. Pretty sure you can also alias lodash with webpack to an even lighter build if this is really a massive concern.

I would argue that if a diagramming reliant application was suffering because of 30kb, then something else might be going wrong. Anyways, I would prefer to keep it this way it is, not introduce more entropy in the code and not rely on the structure of lodash, bundled with the fact that this library is getting re-written anyways.

🤷‍♂️

**Comment by af** [comment]
@dylanvorster What issues have you run into when importing only the used functions from lodash? It would be nice to get more tree-shaking benefit from webpack here if possible, but I'm genuinely curious what the drawbacks of that form of import are.

**Comment by dylanvorster** [comment]
As per discussion, closing this for now.
