### ISSUE TITLE
Regenerate engine

### ISSUE THREAD

**Issue by abhiravredox** [projectstorm/react-diagrams#318]
I want to make a diagram and save it in DB as a JSON (as a string maybe) and then reload the diagram using the db entry. I tried doing this by passing the parsed json.
Something like this:
var model = new DiagramEngine(oldModel);

but the new model doesn't have the nodes and link of the new model.

Please help!
Thanks in advance.

**Comment by moyeradon** [comment]
I actually have solved this for doing this in my own work as I ran into the same issue. You're really close, but just need to be mindful of the format in which you give the serialization. 

You can follow the serialization demo fairly closely, the only difference being that you are grabbing the JSON from your DB entry instead of the existing model in the demo.

I've solved this using MySQL by setting the "layout" attribute on my "chart" model to type `text`. Then, you can stringify the JSON and save it to that field. (I imagine you could also do this with Postgres using the `json` field type and you could probably skip the parse in the code below.) 

```
JSON.stringify(model.serializeDiagram());
```

When you pull the "layout" field back out, you can parse the JSON and send it to the `model.deSerializeDiagram` function like so (where layout is the stringified JSON of your model): 

```
const engine = new DiagramEngine(),
        model = new DiagramModel();

model.deSerializeDiagram(JSON.parse(layout), engine);
engine.setDiagramModel(model);
```

The reason that nothing is showing up is because the format is being passed as a string (or incorrectly) to `deSerializeDiagram`.

There is also no need to reset the engine to the model, like you did in your example as all you want to do is tell it what content to display via the deserialization.

I have also solved this with `react-rails` using a Rails model and the `serialize :layout` code on my Chart model using the same code.

Hope this helps!

**Comment by abhiravredox** [comment]
Thanks a lot! I ended up recreating the nodes and edges from the parsed json.
This also works, Thanks.

**Comment by Smitgamit** [comment]
@abhiravredox 
> Thanks a lot! I ended up recreating the nodes and edges from the parsed json.
> This also works, Thanks.
 sir can you explain in details with file names
