### ISSUE TITLE
Diagrams not displaying

### ISSUE THREAD

**Issue by ghost** [projectstorm/react-diagrams#319]
Using the examples provided the diagrams are not displayed (This issue was closed but the suggestion does not work on the latest version (https://github.com/projectstorm/react-diagrams/issues/169) and (https://github.com/projectstorm/react-diagrams/issues/144).

I assume there is an issue with the css file, so can this be updated to get a simple example running (using Create React App) without having to have to try to hack the css files?

**Comment by DigitalFlow** [comment]
When using the plain examples, you have to make sure that each parent html node is set to height 100%, otherwise the diagram will not be visible.

Even the html element will have to be set to 100% height, as well as the body and so on.
Alternatively, you can overwrite the srd-diagram css class to change to position property to static.
