### ISSUE TITLE
How delete links without targetPort linked

### ISSUE THREAD

**Issue by edwinjoel1984** [projectstorm/react-diagrams#415]
Hello.

I am trying to create a series of connected nodes, but I have not been able to control when a link is created without a target.

![links](https://user-images.githubusercontent.com/16127460/64047971-ea880a00-cb35-11e9-9d2e-a2d208faa2d1.png)

Any help would be very useful.

**Comment by timrbula** [comment]
@edwinjoel1984 Were you able to figure out an approach for this?

**Comment by TranVanKung** [comment]
This how I make it work. 
In diagramModel, I add an event listener:
` diagramModel.addListener({
      linksUpdated: this.removeNotValidLink,
    });`

When you created new link, or update targetPort of a link, linksUpdated() event should be call, and then trigger function removeNotValidLink(). On removeNotValidLink(), I map though all link and remove which have targetPort === null. For better user experience and performance, I will trigger removeNotValidLink() after 10s since the last event listener linksUpdated() call, and delete all previous setTimeout()
`removeNotValidLink = () => {
    if (checkValidLinkTimeout) {
      clearTimeout(checkValidLinkTimeout);
    }
    checkValidLinkTimeout = setTimeout(() => {
      const model = app.getDiagramEngine().getDiagramModel();
      const listLink = Object.values(model.getLinks());
      listLink.forEach(link => {
        if (!link.targetPort) {
          model.removeLink(link);
          // console.log('invalid');
          this.forceUpdate();
        }
      });
    }, 10000);
  };
`
I hope that work for you!

**Comment by wevek** [comment]
Hi there folks in the future

link.targetPort is a protected property

`			<S.Body onMouseUp={() => {
				const model = this.props.app.getModel();
				const listLink = Object.values(model.getLinks());
				listLink.forEach(link => {
					if(!link.getTargetPort()){
						model.removeLink(link);
					}
				});
			}}>`

That's how I did it, thanks!
