### ISSUE TITLE
PortWidget port null error

### ISSUE THREAD

**Issue by quangas** [projectstorm/react-diagrams#455]
Any ideas how to resolve this issue? It's from the TSCustomNodelWidget demo.

`Type 'PortModel<PortModelGenerics> | null' is not assignable to type 'PortModel<PortModelGenerics>'.`

`Type 'null' is not assignable to type 'PortModel<PortModelGenerics>'. TS2322`

For

`<PortWidget port={this.props.nodeModel.getPort('in')} ... />`

**Comment by ishanshukla97** [comment]
Hey @quangas  I got stuck in the same issue. Mind sharing how you resolved this?

Thanks!

**Comment by noahtren** [comment]
I had this same bug and think I resolved the problem by changing the type definition of `PortWidget.port` from `PortModel` to `PortModel | null`, so that it matches what `getPort` returns. This would be in the `PortWidget.d.ts` file in your node modules folder.

Note: I'm very new to TypeScript and web dev in general and I'm not sure if this was a bug in the package or if I'm just doing something very wrong. Hope this helps someone. :)

**Comment by brucean52** [comment]
I fixed it by changing  strict to 'false' in tsconfig.json

**Comment by jMoulis** [comment]
I think the solution should not to downgrade the level of typescript but adding a `null` to the PortProps.port interface

**Comment by danielmcquillen** [comment]
Encountering the same issue. @jMoulis does your approach involve forking the project and then adjusting to something like the following (adding an optional marker to port?) 

```
export interface PortProps {
	port?: PortModel;
	engine: DiagramEngine;
	className?;
	style?;
}
```

(If so, wondering if there's an easier approach that doesn't involve forking project and building from that. Not great with Typescript so apologies if the answer is obvious.)
