### ISSUE TITLE
How can I learn more about architecture of the project?

### ISSUE THREAD

**Issue by sg1705** [projectstorm/react-diagrams#474]
I'd love to learn more about the internals and architecture of react diagrams, and I'd love to contribute to documentation. But I am not sure how where to start. @dylanvorster any tips?

**Comment by kbruskiewicz** [comment]
As some hints:
- It's not a typical React project in that it predominantly maintains its own state and event handling. This might make it difficult to relate to a React codebase if your primary background is just in React (although it can be done, see this port: https://github.com/woodenconsulting/react-js-diagrams).
- It's also not a typical React project in that it's primarily an object- and inheritance-driven codebase, rather than using declarative, presentational components as has become the norm since React v16 and the introduction of hooks.

Particularly in v6 it looks like the devs have consistently applied the Factory Pattern across all of their entities. So everything from the diagram itself to its nodes and links has internal state, a widget to render it, and a factory to construct it for pushing into the engine. Likewise their event-handling system looks custom and is probably driven by their work done in @projectstorm/react-canvas-core.

I haven't found a graph/diagram component written in React that hasn't had to create a thick client to prevent compromising its functionality. So this shift to these idioms is understandable.
