### ISSUE TITLE
Programmatically set state

### ISSUE THREAD

**Issue by garrettmaring** [projectstorm/react-diagrams#496]
I'm trying to save the diagram state when the component unmounts and render the diagram with the saved state when it remounts. The hook looks roughly like this.

```typescript
const useDiagramControlledState = (engine?: CanvasEngine, state?: State) => {
  useDeepCompareEffect(() => {
    if (engine && state) {
      engine.getStateMachine().setState(state);
      engine.repaintCanvas();
    }
  }, [state]);
}
```

This doesn't seem to have any impact on the diagram. The links are still present.

How does one set the state of the Diagram. Similarly, I wanted to implement a "reset" function to clear all of the state. I ended up manually iterating through the links and removing them. I feel as though it'd be cleaning if I was just able to override the state.

**Comment by jling90** [comment]
There's a bit of terminology confusion here. The engine's stateMachine is an event bus that's used to handle event handlers like mouse clicks/key presses. So the 'state' we're looking at here might not be what you're looking for. If my guess is correct, you're looking for 'state' such as nodes and edges on the graph. These entities are stored inside the engine's model.

I'm not sure whether this works for your usecase, but you can serialize the model state to a string and rehydrate as per [this demo](https://github.com/projectstorm/react-diagrams/blob/ce38f77027ac37ca9193c6faccc6049036906e42/packages/diagrams-demo-gallery/demos/demo-serializing/index.tsx). Otherwise if you're maintaining state externally, you can update/reinitialise the model inside your hook e.g.

```js
const useDiagramControlledState = (engine?: CanvasEngine, models?: BaseModel[]) => {
  useDeepCompareEffect(() => {
    if (engine && state) {
      const newModel = new DiagramModel();
      newModel.addAll(...models)

      engine.setModel(newModel);
      engine.repaintCanvas();
    }
  }, [state]);
}
```

**Comment by garrettmaring** [comment]
Thank you! I was confused there. I appreciate the answer 👍
