### ISSUE TITLE
Using blocky shapes as custom nodes

### ISSUE THREAD

**Issue by mattbishop** [projectstorm/react-diagrams#504]
I am considering using react-diagrams in a Google Blockly project to create and display edges between blocks. The blocks are SVG elements so I think the basic approach would be to create custom Nodes in react-diagrams that fetch their SVG shapes from the blocky scene graph.

More information about Blockly here: https://developers.google.com/blockly

My question is has this been attempted by others, or have others tried something similar?

Is there a react-diagrams newsgroup / slack that would be a good place to discuss?

**Comment by renato-bohler** [comment]
Hey @mattbishop!

> My question is has this been attempted by others, or have others tried something similar?

I'm developing a project which is using `react-diagrams` with custom nodes with SVG shapes. The project is still very new, so there's not much to it... and it may not be the best reference, because I'm trying to build an entire API on top of `react-diagrams`... but yeah, what you want to do is achievable and I'm doing it :smile:. For example:

![logossim](https://i.imgur.com/voMgFiM.png)

Those nodes on this diagram are imported from an SVG file and styled using `styled-components`. This one is still pretty simple, but since it is a React component, you'll be able to implement basically any shape and/or functionality (AFAIK).

You can check out the source code on [this repository](https://github.com/renato-bohler/logossim). More specifically, [this](https://github.com/renato-bohler/logossim/blob/51f44d229483182e4a071c97faaa4018e8afd7c2/packages/%40logossim/components/And/And.jsx) is where the "widget" of this node is located.

> Is there a react-diagrams newsgroup / slack that would be a good place to discuss?

Yes! There's a [Gitter channel](https://gitter.im/projectstorm/react-diagrams).

**Comment by mattbishop** [comment]
Thank you for taking the time to tell me about the logossim project! See you on gitter.

**Comment by renato-bohler** [comment]
I think this issue can be closed @dylanvorster
