### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by kneeinnovation** [projectstorm/react-diagrams#547]
I'm trying to do serialization and deserialization of my canvas. Serialization happens correctly, but deserialization gives me error TypeError: i.deserialize is not a function. From what I discovered it tries to call deserialize function of my custom node factory, which isn't implemented. I looked at default node factory code and didn't find implementation of that method. So question is: what should I do to successfully deserialize my canvas?

Thanks in advance to your answer!

**Comment by renato-bohler** [comment]
Serialization and deserialization functions are implemented on models rather than factories.

For example, the [DiamondNodeModel](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeModel.ts) extends from [NodeModel](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/node/NodeModel.ts), which override `serialize` and `deserialize` inherited from [BasePositionModel](https://github.com/projectstorm/react-diagrams/blob/27022d2965a7589812606b5e3b5606ad0659d1ae/packages/react-canvas-core/src/core-models/BasePositionModel.ts) and so on.

**Comment by kneeinnovation** [comment]
> Serialization and deserialization functions are implemented on models rather than factories.
> 
> For example, the [DiamondNodeModel](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeModel.ts) extends from [NodeModel](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/node/NodeModel.ts), which override `serialize` and `deserialize` inherited from [BasePositionModel](https://github.com/projectstorm/react-diagrams/blob/27022d2965a7589812606b5e3b5606ad0659d1ae/packages/react-canvas-core/src/core-models/BasePositionModel.ts) and so on.

Great! Thank you!  We found out that some of factory methods returned factory instead of node.

**Comment by pierre-moire** [comment]
I am closing this ticket has it has been answered more than a month ago. Please feel free to reopen if needed
