### ISSUE TITLE
Request for complex example source code

### ISSUE THREAD

**Issue by maximizeIT** [projectstorm/react-diagrams#56]
Hey there,
would it be possible if you could upload the source code for the example seen on this picture: https://github.com/projectstorm/react-diagrams/blob/master/images/example1.png ? :) 
I would really much appreciate it! 
Cheers, Max

**Comment by giladkhen** [comment]
+1

**Comment by squirmsound** [comment]
+1

**Comment by tylerjharden** [comment]
Would also like to see this. It is a full 180 from what the actual code and demos show for this library.

**Comment by dylanvorster** [comment]
well its not exactly a full 180. I just made my own blocks with borders and neatly arranged them on a cool background.

http://i0.kym-cdn.com/entries/icons/facebook/000/006/026/NOTSUREIF.jpg

**Comment by tylerjharden** [comment]
@dylanvorster Not sure why this is closed. As it stands now your library (for having 591 stars on GitHub) has no documentation and doesn't work. I killed 8 hours last night trying to hack together code from the demos to work, and it frankly doesn't.

The hook that gets people to want to try this library, and the way I intend to use it, as I'm sure many others do, is more in line with your example image where you made your own blocks with borders and arranged them neatly. That's your example image, but for some reason you don't have that as a demo or show it? And when several people ask for it you close the issue with no reason why you wouldn't share?

I can't even get your basic examples working because the terseness and storybook dependency, there is no example of using this outside if within itself. I'm more than willing to contribute back and help others but it would be extremely helpful for everyone if you could 1) share the source behind those nodes in that image and 2) offer an example application that includes this library from NPM and works correctly.

**Comment by dylanvorster** [comment]
@tylerjharden Dear tylerjharden

While I appreciate your interest in my library which I Open-Sourced simply to share it with the world, I would like to clear up a few things.

"As it stands now your library (for having 591 stars on GitHub) has no documentation" You are more than welcome to contribute some, but this library is actually very much still in its infancy, and due to the nature of it changing all the time, I have opted for extremely verbose demos instead.

Also I don't control how many stars my library has, but it does simply mean that 591 people hopefully like, and I assume understand what I have written.

"and doesn't work" Strange, the examples work fine on my side, and the live demo you can find here:

http://www.projectstorm.io/react-diagrams

"That's your example image, but for some reason you don't have that as a demo or show it?" The reason is explained here:

https://gitter.im/projectstorm/react-diagrams?at=590d7ca2d1a7716a0a9a5bc2

`hey guys sorry for only getting back to you all now
I switched jobs this week after 7 years, so I had quite a transition period in my life to say the least xD
so example1.png is my own personal project and so unfortunately I can't release the source code for all those nodes and widgets.
I might at a later point make a separate project that contains some sort of node/widget pack that we can all use`

"And when several people ask for it you close the issue with no reason why you wouldn't share?"

Take a look at who closed the issue before you attack me like this please.

"I can't even get your basic examples working because the terseness and storybook dependency"

honestly, just spin up a new project, add it as a dependency and try again. Or why don't you ask other people in the chat (or here) how they do it. For what its worth, spinning up the project with yarn is supposed to be something that is incredibly basic, so if you struggling to get that basic thing going, then either there is a breaking dependency, or you are missing something basic completely.

"of within itself, non-compiled." there is a dependency page on GitHub that will Kindly point you to a number of community driven projects that make use of this library outside of the demos.

"offer an example application that includes this library from NPM and works correctly." see my previous point.

If I sound rude, its because you word your entire response as though I "owe it to you" and am "obligated" to help solve your specific problem and "should have already" with better documentation. I don't have the time to hold people's hands and show them how to code, but the few people here that are really invested in this library, did so with a much better attitude, and actively engaged with me through chat and pleasant conversation to help me figure it out.

I didn't think I was going to need a community guidelines file, but I think I'm going to have to invest some time in this. I appreciate how you are engaging here in the issues section, but If you can make your annoyances more granular and more technical rather than project bashing, than I would be more than willing to try and help you.

The tagline of my project is "it just works" because I would like to think it does given the live demos page that is constantly in sync with the published version on NPM.

**Comment by tylerjharden** [comment]
I appreciate your response, and bashing your project is the farthest from my intent. I apologize, as I only noticed the originator closed the issue after I made my comment.

Also, being that Gitter isn't extremely common in the environments I work in, didn't think to check there and read the history from months back to find out that your example picture is a closed-source personal project. May I kindly suggest you note that the example image used in the README is not of an example included in this project, but rather an example of what you have been able to do with this library in a closed-source project, to avoid someone else falling into the same confusion I did?

In regards to being owed anything, or any sort of obligation, you market your efforts across several libraries as an effort to making things easier, and I only found your library because several hours of research looking for a library to address the need for an interactive diagramming / flow chart library always resulted in this repo as the top result, with everything else being even more sup par. Apologies for my ignorance in applying the standard expectations I have when I search "distributed task manager for python" and see "Celery" to "react flow diagramming library" and get "react-diagrams" and expect it to be documented and battle-tested to the degree any other React components are given it's community. That's my own fault for not noting how young this library is, or your positions.

I still stand by my point, however that:
1. There isn't any documentation, as all of your demos are baked into the library repo. They use storybook, and while they do convey how to use the library in this bespoke context, or address the technical approaches to the concerns they address individually, react-diagrams is lacking a fully featured demo that imports the library externally to itself.
2. It is of my own personal opinion if you intend to make an open-source library to share with others you can handel the occasional individual like myself who is taken aback when something doesn't meet their expectations. I apologize for the miscommunication, and I appreciate your efforts.

I'll read more into GitHub's dependency graph to look at some project's using this library, and participate in the Gitter for help. 

Cheers!

**Comment by dylanvorster** [comment]
Thanks for understanding, and thanks for pushing through. I purposely called this library storm-react-diagrams because I was not yet confident that this should be the go-to library on NPM for react diagramming. I do think you are right, but time is not something I have much of unfortunately. I try and free up a weekend once a month and try to address a lot of the concerns in one go, and in the next sprint I am definitely going to try and beef up the examples and/or include some more documentation.

What is lacking is an actual site that this project can live in, and I do hope to get to that soon. This is my first proper open-source project, and as such there are still some glaring frustrations with it (as Im more than aware).

I really do appreciate your frustrations though, because it shows that it needs to evolve further. I hope this project will be very different in the next few months, and that the community will rally together to try and get it up to scratch.
