### ISSUE TITLE
force node re-render with custom variables

### ISSUE THREAD

**Issue by bl96** [projectstorm/react-diagrams#585]
Hello guys, i have made a custom node with my own variables. Model looks like that:
```
export class UnBinaryNodeModel extends NodeModel<NodeModelGenerics & UnBinaryNodeModelGenerics> {
	unaryPredicates: Set<string>;
        unaryPredicateIndex: number;
	appendPort: UnBinaryPortModel;

	constructor(name: string, color: string, reduxProps: any);
	constructor(options?: UnBinaryNodeModelOptions);
	constructor(options: any = {}, color?: string, reduxProps?: any) {
		if (typeof options === 'string') {
			options = {
				name: options,
				color: color,
				reduxProps: reduxProps,
			};
		}
		super({
			type: 'unbinary',
			name: 'Untitled',
			color: 'rgb(92,192,125)',
			...options
		});
		this.registerEvents();
                this.addTemplatePorts();
		this.unaryPredicates = new Set();
	}
```

And in node widget i have a port which is adding strings into ```unaryPredicates```:
```
<PortWidget engine={this.props.engine} port={this.props.node.getAppendPort()}>
							<PortS onClick={() => {
								this.props.node.addUnaryPredicate(`Pred${this.props.node.unaryPredicateIndex}`);
								this.forceUpdate();
								//this.props.engine.repaintCanvas(); -> update is not performed
							}}
								   height={20} width={this.props.node.getOptions().name.length * 20}>{ADDPORT}</PortS>
						</PortWidget>
```

If i understand it correctly ```engine.repaintCanvas()``` will call ```generateWidget()``` for those models which state was changed. But changing my own variables will not trigger state change. For example changing node default variable ```locked``` will cause state change.

My question is how can i achieve this? Calling ```this.forceUpdate()``` instead of ```engine.repaintCanvas()``` will resolve my problem but i want it to happen every time when any of widget´s props are changed. Thanks in advance for reply.

**Comment by renato-bohler** [comment]
Hey @bl96.

This is probably what is happening: `react-diagrams` has this [PerformanceWidget](https://github.com/projectstorm/react-diagrams/blob/4a57ecdc97d319986f12cb8e84112e2d3cd5f946/packages/react-canvas-core/src/widgets/PeformanceWidget.tsx#L14) to update entities only if:

- performanceTune is set to false **OR**
- on deserialization **OR**
- if the serialized model changes

Currently, none of these conditions are being met, so your node will not rerender. Overriding `performanceTune` to return `true`would make it rerender, but it would cause performance issues.

So, long story short: you'll have to override at least the `serialize` method to add your custom variables to the serialized model, so that it changes and the node updates. Something like that:

```JavaScript
serialize() {
    return {
      ...super.serialize(),
      // You may need to transform these to be serializable
      unaryPredicates: this.unaryPredicates,
      unaryPredicateIndex: this.unaryPredicateIndex,
      appendPort: this.appendPort, // especially this one, since its a Model
    };
  }

  deserialize(event, engine) {
    super.deserialize(event, engine);
    // You may need to transform these to deserialize them
    this.unaryPredicates = event.data.unaryPredicates;
    this.unaryPredicateIndex = event.data.unaryPredicateIndex;
    this.appendPort = event.data.appendPort; // especially this one, since it was a Model
  }
```

Hope it helps.

**Comment by bl96** [comment]
It works. Thank you so much @renato-bohler :) I will close this issue.
