### ISSUE TITLE
Are there any listeners when node's extras are changed?

### ISSUE THREAD

**Issue by pmehta18** [projectstorm/react-diagrams#648]
Hi!

Firstly thanks for this awesome library, it's really useful.

I would like to know here that if we have any listeners which we can set for getting events when the "extras" from any node is updated.

I am using version 5.2.1

Thanks in advance!

**Comment by renato-bohler** [comment]
Hmm I don't think so... but why do you need this?

**Comment by pmehta18** [comment]
I need for maintaining it in stack for undo/redo operations

**Comment by renato-bohler** [comment]
Hmmm well, you could try and do something like this:

1. Add `setExtras` method to your `Model` class and use it instead of mutating the `extras` object directly;
2. On this `setExtras` method, call `this.fireEvent(this.options.extras, 'extrasChanged')`;
3. Now you can listen to `extrasChanged` event.

Alternatively, if you don't want to change the way you mutate `extras`, maybe you can make this object a [`Proxy` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), and call `this.fireEvent` on every `set` handler... but personally I think this is overcomplicating hehe

**Comment by agarwalishan** [comment]
@renato-bohler can you please tell how I can serialize this setExtras method so that when I deserialize I can use 'extrasChanged' listener. Actually I want custom listeners for some actions related to node but I do not know if we can make a custom listener to the node and use it after deserilization. Please help...

**Comment by agarwalishan** [comment]
Yes you are right, I did some mistake sorry.

**Comment by dylanvorster** [comment]
@renato-bohler is correct in his advice, closing for now
