### ISSUE TITLE
tslint + editor config

### ISSUE THREAD

**Issue by kvolkovich-sc** [projectstorm/react-diagrams#65]
Hi! :smile: 

What do you think about:

* Add [editorconfig](http://editorconfig.org/) for ends of lines and indent consistency 
* Add [tslint](https://palantir.github.io/tslint/) for code formatting checking
* Follow [Microsoft TypeScript coding guidlines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) (at least swith indent from **tab** => **2 spaces**)
* [Add Microsoft TypeScript config](https://github.com/Microsoft/tslint-microsoft-contrib)
* Add [travis-ci](https://travis-ci.org/)

I think these automatic quality checking tools are helpful :eyeglasses: for open-source project.
I can make a PR if you wish.

**Comment by dylanvorster** [comment]
Hi There

I am a fan of adding all those tools, but I am not in favor of switching to spaces for a plethora of reasons. I work in spaces because I work in 4 spaces for a tabs.
* There is already a tsconfig
* there are no tests at the moment, and testing is going to be very difficult, so adding Travis will only be useful if we finally have tests.
* there is a tsint that I use already which I will commit at some point.

**Comment by kvolkovich-sc** [comment]
Then at least add .editorconfig. When switching across different projects with different code-styles, it very helpful.

**Comment by dylanvorster** [comment]
have started implementing some of this on dev branch
