### ISSUE TITLE
Zooming out doesn't increase the playing area?

### ISSUE THREAD

**Issue by jmlevesque333** [projectstorm/react-diagrams#666]
Hi, I'm pretty new to react-diagram, so I'm not too sure if this is a bug on my end or the library itself, but when I zoom out, it doesn't increase the width nor the length of the playing area? Here's a screenshot where I zoomed out a little bit and I can access the area that wasn't visible at first at normal zoom.

![image](https://user-images.githubusercontent.com/16888975/86130167-283d2280-baba-11ea-8e0a-0fcaa822946f.png)

I dug around in the previous issue and didn't see this mentioned, so sorry if it was already brought up.

**Comment by renato-bohler** [comment]
The only way I could reproduce this is by adding `overflow: hidden` on the `react-diagrams` svg element which represents the link layer:

![image](https://user-images.githubusercontent.com/25781956/86135560-612cc580-bac1-11ea-8e3e-472794329eaf.png)
![image](https://user-images.githubusercontent.com/25781956/86135593-6d188780-bac1-11ea-86a1-cc98d5aad341.png)

Given that it works properly on this [storybook example](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--simple-example), I would say that this is probably caused by some CSS being applied on your project.

**Comment by jmlevesque333** [comment]
Okay thank you for the quick answer, I'll check it out.

**Comment by jmlevesque333** [comment]
I fixed it by using the className prop with this:
`const useStyle = makeStyles(theme => ({
	myCanvas: {
		overflow: 'visible'
	}
}));`
