### ISSUE TITLE
Add self reference relation

### ISSUE THREAD

**Issue by Tohid1999** [projectstorm/react-diagrams#703]
Hello
how can i create a link that connected to some another port form that same table (self reference relation)

![Untitled](https://user-images.githubusercontent.com/38454327/91006680-48d3b580-e5ef-11ea-96ea-cf8505b76c71.png)

**Comment by renato-bohler** [comment]
By default, the `PortModel` exported by the project allows ports to connect to any other port:

https://github.com/projectstorm/react-diagrams/blob/c9f7d2c5160bfd3f932a6cd3bccd6b0a3bb8a0cd/packages/react-diagrams-core/src/entities/port/PortModel.ts#L153-L155

So if you're not being able to connect a port to another port, it may be the case that you are using `DefaultPortModel`, which allows only input ports to connect to output ports (and vice-versa):

https://github.com/projectstorm/react-diagrams/blob/51c6bd2391f7a122a114b2bac1965e7957744b1d/packages/react-diagrams-defaults/src/port/DefaultPortModel.ts#L61-L66

I don't know exactly what your requirements are, but you basically have two options:
- use `PortModel` instead of `DefaultPortModel` (if you are really using `DefaultPortModel`)
- override `canLinkToPort` method of your `PortModel` (or add a custom port model, if you haven't)
