### ISSUE TITLE
How can i prevent remove nodes and links ?

### ISSUE THREAD

**Issue by newzpanuwat** [projectstorm/react-diagrams#705]
I want to prevent remove only nodes and links,  except point which i created 

example -> i have 2 node and 1 link and i added more 2 points
how can i disable each node and this link, but allow remove these points

Anyone can help, Thanks a lot 
![Screenshot from 2020-08-24 14-53-54](https://user-images.githubusercontent.com/14777584/91018346-aaa91500-e619-11ea-8ff3-c8626d91f6bb.png)

**Comment by renato-bohler** [comment]
You can customize the delete action following [this example](https://github.com/projectstorm/react-diagrams/blob/655462087f1f54eccb5e75f024be00efda674eab/packages/diagrams-demo-gallery/demos/demo-custom-action/index.tsx) ([link to storybook](http://projectstorm.cloud/react-diagrams/?path=/story/customization--custom-event)).

Here, you have access to a list of all selected entities (nodes, links, points). You can implement a filter to call `model.remove` only on those you want, instead of asking for confirmation.

https://github.com/projectstorm/react-diagrams/blob/655462087f1f54eccb5e75f024be00efda674eab/packages/diagrams-demo-gallery/demos/demo-custom-action/index.tsx#L24-L38
