### ISSUE TITLE
Help with grouping nodes into columns

### ISSUE THREAD

**Issue by Fl0rianFischer** [projectstorm/react-diagrams#717]
Hi!

First of all thank you for this great library! I'm currently working on a tool to visualize supply chains. For this we cluster locations into steps on a supply chain. So e.g. the step "Origin" might have the locations (nodes) "Berlin" and "Leipzig". I attached a screenshot of a wireframe to make it more understandable. Do you have any suggestions on how to achieve this?
![Screenshot 2020-09-09 at 15 24 32](https://user-images.githubusercontent.com/8488432/92604617-ffeb5480-f2b0-11ea-982e-3b08f537978f.png)

**Comment by renato-bohler** [comment]
Hey there!

Using `react-diagrams` for your use case seems doable, but in all honesty, I would probably consider implementing a custom solution for this.

The main reason for that is because `react-diagrams` doesn't officially support grouped nodes. This "steps" header seems like a node in which every step is a child node. As far as I know, this is doable, but I've never seen anything open source to refer to. Other problem is that you have this tabular layout... every time you add or remove a step or location you would have to adjust this table height and width manually.

On the other hand, if you choose to use `react-diagrams` you'll benefit from zoom, panning and serialize/deserialize features. So if you really want to use it, here's what I would do (on a very high level):

- create a background node to visually simulate this tabulated layout (header, columns, etc.)
  - this node would always be on the diagram, behind all other nodes
- create step node
- create "add step button" node
- create location node
- create "add location button" node
- change `MoveItemsState` to disable the moving of nodes
- create logic to update the diagram whenever a step or location is created/removed
  - the background node width would have to be increased when a new step is added
  - the background node height would have to be updated when a new location is added
- create logic to add and position step/location nodes
- create a custom link with arrow head (there's an example on storybook)
- create a custom port that only allows connecting locations from one step to a location on the next step

**Comment by Fl0rianFischer** [comment]
Thank you so much for your suggestions! 

How would you go about creating your own solution? I think the column layout with nodes etc. could be achieved quite easily. What I'm struggling with is to find a concept to create custom Links outside of a `react-diagrams` context.

**Comment by renato-bohler** [comment]
I would implement a port component which responds to `onDragStart`, `onDrag` and `onDragEnd` to create links.

Searching a little bit, I've found this [example on codesandbox](https://codesandbox.io/s/so-drag-anim-pending-3r69z?fontsize=14&hidenavigation=1&theme=dark&file=/src/Example2.jsx). You would need to implement link selection and removing, probably, but that's a good starting point I guess.

**Comment by Fl0rianFischer** [comment]
Thank you so much for your help!

**Comment by renato-bohler** [comment]
Hey @Fl0rianFischer 

I've just stumbled upon this, might be useful for your use case aswell: https://github.com/uber/react-digraph

**Comment by shahsuvarli** [comment]
Hi, @Fl0rianFischer. I was curios if you could find any solution for your use case?
