### ISSUE TITLE
Can links become visible above node?

### ISSUE THREAD

**Issue by agarwalishan** [projectstorm/react-diagrams#749]
Hey, When we make links then they appear by default below node. Is there any way by which we can show them above nodes like in pic below?
![image](https://user-images.githubusercontent.com/41884267/96579255-2e1e7400-12f4-11eb-9ce7-1b2e5a7261ad.png)

**Comment by renato-bohler** [comment]
You can add `z-index: 1` to the `svg` element inside `react-diagrams`.

**Comment by agarwalishan** [comment]
@renato-bohler Thank you very much it's working perfectly. But could you please explain how it worked, I don't understand the reason?

**Comment by renato-bohler** [comment]
Sure. So this is how `react-diagrams` looks in the DOM:

![image](https://user-images.githubusercontent.com/25781956/96716903-14287400-137c-11eb-98d6-3397303195ee.png)

Where:

1. Is the `react-diagrams` container
2. Is the link layer. Every link is rendered inside this `svg`.
3. Is the node layer. Every node is rendered inside this `div`.

Both the link and node layer have `position: absolute` but no `z-index`. Because `div` comes after `svg`, the nodes are rendered above the links as default. When you set `z-index` to `1`, you are telling the browser that all links should be rendered above the nodes.

https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by agarwalishan** [comment]
@renato-bohler Thank you very much for explaining, I got it. Could you please tell me if there is any event that fires when we click on canvas?

**Comment by renato-bohler** [comment]
Hmmm I think there isn't. Not sure why you need that, but you could maybe `addEventListener('click')` on the canvas. If you need more information of where the click happened or anything like that, you'll probably need to implement a custom state which fires this event.

**Comment by agarwalishan** [comment]
@renato-bohler Ok, Is there a way to deregister default registered state? Actually I want Undo/Redo on moving items and I saw your code of logossim for implementing where you have made a custom MoveItemsState. I also want to implement like this but the problem is I have not made a Custom Diagram Engine like yours rather I am using default engine that react-diagrams provides and which comes with some states already registered in it as mentioned here.

[https://github.com/projectstorm/react-diagrams/tree/3e69dafef9a0b4bc9aa0d1be5c93ef542ad32aa7/packages/react-canvas-core/src/states](url)

So how can I de-register existing MoveItemsState and register my new custom inplace of it?

**Comment by renato-bohler** [comment]
You just need to call `engine.getStateMachine().pushState()` with your custom `State` class. [Here's how I did it](https://github.com/renato-bohler/logossim/blob/415a263/packages/%40logossim/core/Diagram/DiagramEngine.js#L45-L47).

**Comment by agarwalishan** [comment]
@renato-bohler  Ok thanks, your logossim project helped me a lot

**Comment by sinanyaman95** [comment]
> You can add `z-index: 1` to the `svg` element inside `react-diagrams`.

It seems like I can't link two ports now, as they are behind the link element. Any workaround for that?

**Comment by agarwalishan** [comment]
> > You can add `z-index: 1` to the `svg` element inside `react-diagrams`.
> 
> It seems like I can't link two ports now, as they are behind the link element. Any workaround for that?

Sorry but I am not using drag and drop feature for making link. I am connecting links programmatically. Aren't you even able to create atleast one link?

**Comment by vivekshah-zymr** [comment]
> > You can add `z-index: 1` to the `svg` element inside `react-diagrams`.
> 
> It seems like I can't link two ports now, as they are behind the link element. Any workaround for that?

Hi @sinanyaman95 , did you find any workaround for this? I am getting the exact same issue. @renato-bohler

**Comment by renato-bohler** [comment]
Uhh crap... well, you could add `z-index: 2` specifically on the ports, but that would make the browser render them on top of links.

I guess a hacky solution you could try is separating the port element into two: one visual and one invisible, making the invisible have the same size and position as the visible, but with `z-index: 2`... not sure if that would introduce any other issues.

If that's not desirable, I think the only alternative is changing how `react-diagrams` handles click with a custom state, trying to figure out what element the user is trying to click in (instead of using `getModelForEvent`). That can be complex, tough...

**Comment by vivekshah-zymr** [comment]
@renato-bohler 
After setting svg z-index to 1, I have already tried to add z-index of higher number to the port, but it's not working, as the main(parent) div for that port is having z-index 0 by default. So we are not able to pull the link from that port. And if set main/parent port z-index higher than the arrows get hide due to same or lesser z-index of svg tag.

With Z-index value 0 for svg
![zindex0](https://user-images.githubusercontent.com/26891421/151498892-464a27ef-a488-45a8-953e-4a8cb32630a4.gif)

With Z-index value 1 for svg
![zindex1](https://user-images.githubusercontent.com/26891421/151499043-80459768-f381-4d46-9d27-e9149702f781.gif)
 So any better solution you are suggesting?

**Comment by vivekshah-zymr** [comment]
Also @renato-bohler, 
We are working on Nodes which can have multiple ports, so we have added scroll view inside our custom nodes. But when we have links between two ports of two different nodes or two ports of the same node.
So while scrolling the ports inside node, links remains on the same position even if that port gets scrolled up.(See the attachment.) 

![scroll-issue](https://user-images.githubusercontent.com/26891421/151504076-8675509f-e398-45c1-8720-498456d466eb.gif)

Is there anything that you can suggest here to achieve this?

**Comment by renato-bohler** [comment]
> @renato-bohler After setting svg z-index to 1, I have already tried to add z-index of higher number to the port, but it's not working, as the main(parent) div for that port is having z-index 0 by default. So we are not able to pull the link from that port. And if set main/parent port z-index higher than the arrows get hide due to same or lesser z-index of svg tag.

Hmm yeah, that really shouldn't work because of how stacking context works :confused: 

Other thing you could try is removing all layers using [CanvasModel](https://github.dev/projectstorm/react-diagrams/blob/3d0521cc934b1430d6c8f3b109d9ec6d0b19f3e2/packages/react-canvas-core/src/entities/canvas/CanvasModel.ts) `getLayers` and `removeLayer`, and then adding them in reverse order using `addLayer`, similarly to `DiagramModel`:

https://github.com/projectstorm/react-diagrams/blob/3d0521cc934b1430d6c8f3b109d9ec6d0b19f3e2/packages/react-diagrams-core/src/models/DiagramModel.ts#L32-L33

Again, I'm not sure if that would work, since I never needed to do this.

---

> Also @renato-bohler,
We are working on Nodes which can have multiple ports, so we have added scroll view inside our custom nodes. But when we have links between two ports of two different nodes or two ports of the same node.
So while scrolling the ports inside node, links remains on the same position even if that port gets scrolled up.(See the attachment.)

This one I have no clue on how to implement, honestly... it looks very complex, I never succeeded handling port position changing when I tried to make a generic node rotation feature for my project.
