### ISSUE TITLE
How to change the background?

### ISSUE THREAD

**Issue by thn80** [projectstorm/react-diagrams#818]
Hi,

how can the background of the whole diagram be changed? Currently I'm using the "diagrams-demo-project" which shows a gray background color, while all the examples in "diagrams-demo-gallery" have a gray background with a grid.
Where do I have to start when changing the background?

**Comment by sinanyaman95** [comment]
Hey @thn80 , diagrams are wrapped inside a Canvas. All the stories in the storybook for example, are wrapped inside the `DemoCanvasWidget` and that is styled with `emotion`. You can find the style here: https://github.com/projectstorm/react-diagrams/blob/master/diagrams-demo-gallery/demos/helpers/DemoCanvasWidget.tsx (the long linear gradient). That said, you can do the same approach and style the background as you want

**Comment by thn80** [comment]
Thans, this helped.

**Comment by sinanyaman95** [comment]
You are welcome, you can close the issue if you want

**Comment by movahedan** [comment]
I thought that maybe I'd better reopen the issue because my question is related to the background of the canvas. 

Is there any way to have a miro-like background for the canvas? For instance, I want to reposition the background when the user drags the canvas and moves it to another place. 

I have created another div around the canvas, and I'm using these styling rules:

```background-image: linear-gradient(#c7c1c1 1px, transparent 1px),
    linear-gradient(to right, #c7c1c1 1px, #e7e5e5 1px);
  background-size: ${(props) => `${props.zoomLevel}% ${props.zoomLevel}%`};```

It's working correctly while the user tries to zoom in/zoom out. But I don't how to implement the dragging feature. Is it possible? I put the screenshots of a simple page in miro. You can see the background is being repositioned after I zoom-in/zoom-out or even drag the page and move it. 

![image](https://user-images.githubusercontent.com/17516348/181027809-5baa37f9-5609-467c-a782-7d5456abedc1.png)
![image](https://user-images.githubusercontent.com/17516348/181027997-46e7623c-70f0-47c3-b934-3e8455b02edf.png)
