### ISSUE TITLE
Dynamic generating node and automatic positioning

### ISSUE THREAD

**Issue by MBehtemam** [projectstorm/react-diagrams#94]
hi , first thanks for your awsome library, i create nodes and links with `for` loop , now my question is , is this library has any automatic arrangement for positioning  nodes on the page ? if not what do i can for positioning nodes correctly and nicely on page

**Comment by alex-enchi** [comment]
No, but you can do auto-arrangement via [dagre](https://github.com/cpettitt/dagre)
with some limitations. But it works

**Comment by Kepro** [comment]
@alex-enchi  any small demo? how to do it in correct way? please :)

**Comment by slvnperron** [comment]
+1

**Comment by alex-enchi** [comment]
Small update.
I've created a small example of how to use dagre [rdi-94-dagre-example branch](https://github.com/alex-enchi/react-diagrams/tree/rdi-94-dagre-example) 
I'll clean it up this week and make a pull request

### Some important notes: 

Because i don't know yet how to update node position properly (see #107) it'll work only before first render. 

Default for dagre layout direction is top to bottom, it is possible to change it [dagre wiki](https://github.com/cpettitt/dagre/wiki#configuring-the-layout). But there are difficulties if node has ports on all sides of the node. I.e. if distribution is top -> bottom and 2 nodes are connected via ports on the sides there is no way to tell ranking function to keep this 2 nodes on the same level

Example:
Instead of this
![example-not-gona-happen](https://user-images.githubusercontent.com/24417201/32805133-3b716de2-c991-11e7-8ab3-4989e47cf4c4.png)

Dagre will generate that layout
![example-actual-result](https://user-images.githubusercontent.com/24417201/32805134-3b9400b4-c991-11e7-9379-b589879ebdff.png)

**Comment by slvnperron** [comment]
Awesome Alex, can't wait for the PR!

**Comment by alex-enchi** [comment]
PR is more or less ready #112 
But there are still couple of issues to address

**Comment by dylanvorster** [comment]
8b7b32f4edbfac625a4953060c1d62f732af078a

**Comment by kumar-tdx** [comment]
Hi. Is it missing in the latest version?

**Comment by Kepro** [comment]
@kumar-tdx are you serious? post from 2017 that is closed already? :) http://projectstorm.cloud/react-diagrams/?path=/story/3rd-party-libraries--auto-distribute-dagre but demo page is not working... but check source code...

**Comment by kumar-tdx** [comment]
@Kepro Thanks for for quick response. I already checked the source code. I could not find recalculatePortsVisually method in DiagramEngine. So I was wondering if it was removed in the latest version or is there any other way to achieve it?
